version: "3.8"

services: 
  database_qfinances:
    image: postgres
    container_name: qfinances_database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=qfinances
      - POSTGRES_PASSWORD=Ab12345@
      - POSTGRESS_DB=qfinances
    volumes:
      - pgdata:/data/postgres
    links:
      - qfinances_database
    depends_on:
      - qfinances_database
  app:
    build: .
    container_name: qfinancesApp
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
  
volumes:
  pgdata:
    driver: local